server:
  port: 9091
  servlet:
    context-path: "/url-shortener"

spring:
  application:
    name: "url-shortener"

  # MySQL Connection Settings
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  
  # JPA / Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"

# Actuator service endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
