server:
  port: 9091
  servlet:
    context-path: "/url-shortner"

spring:
  application:
    name: "url-shortener"

  # MySQL Connection Settings
  datasource:
    url: "jdbc:mysql://localhost:3306/URL_SHORTENER"
    username: "username"
    password: "password"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  
  # JPA / Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"

# Actuator service endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
