server:
  port: 9091
  servlet:
    context-path: "/url-shortener"

spring:
  application:
    name: "url-shortener"

  h2:
    console:
      enabled: true
      path: /h2-console # Customize the console access path
      settings:
        web-allow-others: true   # add this

  # MySQL Connection Settings
  datasource:
    url: jdbc:h2:file:./data/url-shortener
    username: sa
    password:
    driver-class-name: "org.h2.Driver"
  
  # JPA / Hibernate Settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Automatically creates/updates the database schema

# Actuator service endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true

#logging:
#  level:
#    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.jdbc: DEBUG
#    org.hibernate: DEBUG
